from django.utils.translation import gettext_lazy as _

# ISO 639-1
LANGUAGES = (
    ("AB", _("Abkhazian")),
    ("AA", _("Afar")),
    ("AF", _("Afrikaans")),
    ("AK", _("Akan")),
    ("SQ", _("Albanian")),
    ("AM", _("Amharic")),
    ("AR", _("Arabic")),
    ("AN", _("Aragonese")),
    ("HY", _("Armenian")),
    ("AS", _("Assamese")),
    ("AV", _("Avaric")),
    ("AE", _("Avestan")),
    ("HY", _("Armenian")),
    ("AY", _("Aymara")),
    ("AZ", _("Azerbaijani")),
    ("BM", _("Bambara")),
    ("BA", _("Bashkir")),
    ("EU", _("Basque")),
    ("BE", _("Belarusian")),
    ("BN", _("Bengali")),
    ("BI", _("Bislama")),
    ("BS", _("Bosnian")),
    ("BR", _("Breton")),
    ("BR", _("Bulgarian")),
    ("MY", _("Burmese")),
    ("CA", _("Catalan")),
    ("CH", _("Chamorro")),
    ("CE", _("Chechen")),
    ("NY", _("Chichewa")),
    ("ZH", _("Chinese")),
    ("CU", _("Church Slavic")),
    ("CV", _("Chuvash")),
    ("KW", _("Cornish")),
    ("CO", _("Corsican")),
    ("CR", _("Cree")),
    ("HR", _("Croatian")),
    ("CS", _("Czech")),
    ("DA", _("Danish")),
    ("CS", _("Divehi")),
    ("NL", _("Dutch")),
    ("DZ", _("Dzongkha")),
    ("EN", _("English")),
    ("EO", _("Esperanto")),
    ("ET", _("Estonian")),
    ("EE", _("Ewe")),
    ("FO", _("Faroese")),
    ("FJ", _("Fijian")),
    ("FI", _("Finnish")),
    ("FR", _("French")),
    ("FY", _("Western Frisian")),
    ("FF", _("Fulah")),
    ("GD", _("Gaelic")),
    ("GL", _("Galician")),
    ("LG", _("Ganda")),
    ("KA", _("Georgian")),
    ("DE", _("German")),
    ("EL", _("Greek")),
    ("KL", _("Kalaallisut, Greenlandic")),
    ("GN", _("Guarani")),
    ("GU", _("Guajarati")),
    ("HT", _("Haitian, Haitian Creole")),
    ("HA", _("Hausa")),
    ("HE", _("Hebrew")),
    ("HZ", _("Herero")),
    ("HI", _("Hindi")),
    ("HO", _("Hiri Motu")),
    ("HU", _("Hungarian")),
    ("IS", _("Icelandic")),
    ("IO", _("Ido")),
    ("IG", _("Igbo")),
    ("ID", _("Indonesian")),
    ("IA", _("Interlingua")),
    ("IE", _("Interlingue, Occidental")),
    ("IU", _("Inuktitut")),
    ("IK", _("Inupiaq")),
    ("GA", _("Irish")),
    ("IT", _("Italian")),
    ("JA", _("Japanese")),
    ("JV", _("Javanese")),
    ("KN", _("Kannada")),
    ("KR", _("Kanuri")),
    ("KS", _("Kashmiri")),
    ("KK", _("Kazakh")),
    ("KM", _("Central Khmer")),
    ("KI", _("Kikuyu, Gikuyu")),
    ("RW", _("Kinyarwanda")),
    ("KY", _("Kirghiz, Kyrgyz")),
    ("KV", _("Komi")),
    ("KG", _("Kongo")),
    ("KO", _("Korean")),
    ("KJ", _("Kuanyama, Kwanyama")),
    ("KU", _("Kurdish")),
    ("LO", _("Lao")),
    ("LA", _("Latin")),
    ("LV", _("Latvian")),
    ("LI", _("Limburgan, Limburger, Limburgish")),
    ("LN", _("Lingala")),
    ("LT", _("Lithuanian")),
    ("LU", _("Luba-Katanga")),
    ("LB", _("Luxembourgish, Letzeburgesch")),
    ("MK", _("Macedonian")),
    ("MG", _("Malagasy")),
    ("MS", _("Malay")),
    ("ML", _("Malayalam")),
    ("MT", _("Maltese")),
    ("GV", _("Manx")),
    ("MI", _("Maori")),
    ("MR", _("Marathi")),
    ("MH", _("Marshallese")),
    ("MN", _("Mongolian")),
    ("NA", _("Nauru")),
    ("NV", _("Navajo, Navaho")),
    ("ND", _("North Ndebele")),
    ("NR", _("South Ndebele")),
    ("NG", _("Ndonga")),
    ("NE", _("Nepali")),
    ("NO", _("Norwegian")),
    ("NB", _("Norwegian Bokmål")),
    ("NN", _("Norwegian Nynorsk")),
    ("II", _("Sichuan Yi, Nuosu")),
    ("OC", _("Occitan")),
    ("OJ", _("Ojibwa")),
    ("OR", _("Oriya")),
    ("OM", _("Oromo")),
    ("OS", _("Ossetian, Ossetic")),
    ("PI", _("Pali")),
    ("PS", _("Pashto, Pushto")),
    ("FA", _("Persian")),
    ("PL", _("Polish")),
    ("PT", _("Portuguese")),
    ("PA", _("Punjabi, Panjabi")),
    ("QU", _("Quechua")),
    ("RO", _("Romanian, Moldavian, Moldovan")),
    ("RM", _("Romansh")),
    ("RN", _("Rundi")),
    ("RU", _("Russian")),
    ("SE", _("Northern Sami")),
    ("SM", _("Samoan")),
    ("SG", _("Sango")),
    ("SA", _("Sanskrit")),
    ("SC", _("Sardinian")),
    ("SR", _("Serbian")),
    ("SN", _("Shona")),
    ("SD", _("Sindhi")),
    ("SI", _("Sinhala, Sinhalese")),
    ("SK", _("Slovak")),
    ("SL", _("Slovenian")),
    ("SO", _("Somali")),
    ("ST", _("Southern Sotho")),
    ("ES", _("Spanish, Castilian")),
    ("SU", _("Sundanese")),
    ("SW", _("Swahili")),
    ("SS", _("Swati")),
    ("SV", _("Swedish")),
    ("TL", _("Tagalog")),
    ("TY", _("Tahitian")),
    ("TG", _("Tajik")),
    ("TA", _("Tamil")),
    ("TT", _("Tatar")),
    ("TE", _("Telugu")),
    ("TH", _("Thai")),
    ("BO", _("Tibetan")),
    ("TI", _("Tigrinya")),
    ("TO", _("Tonga")),
    ("TS", _("Tsonga")),
    ("TN", _("Tswana")),
    ("TR", _("Turkish")),
    ("TK", _("Turkmen")),
    ("TW", _("Twi")),
    ("UG", _("Uighur, Uyghur")),
    ("UK", _("Ukrainian")),
    ("UR", _("Urdu")),
    ("UZ", _("Uzbek")),
    ("VE", _("Venda")),
    ("VI", _("Vietnamese")),
    ("VO", _("Volapük")),
    ("WA", _("Walloon")),
    ("CY", _("Welsh")),
    ("WO", _("Wolof")),
    ("XH", _("Xhosa")),
    ("YI", _("Yiddish")),
    ("YO", _("Yoruba")),
    ("ZA", _("Zhuang, Chuang")),
    ("ZU", _("Zulu")),
)
