version: '3.9'

services:
  web:
    container_name: movie-web
    image: movie-api_web:latest
    build:
      context: .
      dockerfile: ./local/django/Dockerfile
    entrypoint: bash
    command: >
      -c "cd /code/app && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    env_file:
      - ../.envs/.local/app.secrets.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - postgres_network
      - default
    restart: unless-stopped

  db:
    container_name: movie-db
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.envs/.local/app.secrets.env
    ports:
      - "5432:5432"
    networks:
      - postgres_network
      - default
    restart: unless-stopped

  redis:
    image: redis:6.2.6-alpine
    networks:
      - postgres_network
      - default
    restart: unless-stopped

networks:
  default:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
