version: '3.9'

services:
  web:
    container_name: web_container
    build:
      context: .
      dockerfile: ./production/django/Dockerfile
    entrypoint: bash
    command: >
      -c "cd /code/app && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    env_file:
      - ../.envs/.production/app.secrets.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - postgres_network
    restart: unless-stopped

  db:
    container_name: db_container
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.envs/.production/app.secrets.env
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
