# Generated by Django 4.0.3 on 2022-03-30 20:24

import core.fields
import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('language', models.CharField(max_length=2)),
                ('overview', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=50, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ('-year', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('country', core.fields.CountryField(choices=[('AU', 'Australia'), ('ZA', 'South Africa'), ('GH', 'Ghana'), ('NZ', 'New Zealand')], max_length=2)),
            ],
            options={
                'ordering': ['-end_period__year', '-start_period__year'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=core.utils.current_year, verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='month')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['year'], name='period_year_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['month'], name='period_month_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['year', 'month'], name='period_year_month_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('year', 'month')},
        ),
        migrations.AddField(
            model_name='network',
            name='end_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='network_end_period', to='core.period'),
        ),
        migrations.AddField(
            model_name='network',
            name='start_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='network_start_period', to='core.period'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='core.genre'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['id', 'name'], name='genre_id_name_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['id', 'title'], name='movie_id_title_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['id', 'genre'], name='movie_id_genre_idx'),
        ),
    ]
