# Generated by Django 4.2 on 2023-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(
                related_name="movies", related_query_name="movie", to="core.genre"
            ),
        ),
    ]
